name       : curl-gnutls
version    : 7.50.1
release    : 2
source     :
    - https://curl.haxx.se/download/curl-7.50.1.tar.gz : 3e392cf600822b817be82d9080b377fcbab70538d5a8bf525a1cd66e157b99ea
homepage   : http://curl.haxx.se
license    : GPL-3.0+
component  : binary.compat
emul32     : yes
summary    : curl-gnutls (GnuTLS version of curl)
description: |
    This package provides binary compatibility only and enables the running of content expecting a GNUTLS version of curl. It is forbidden to build against it.
builddeps  :
    - pkgconfig32(gnutls)
    - glibc-32bit-devel
    - libgcc-32bit
    - libtool-32bit
setup      : |
    %patch -N -p1 < $pkgfiles/0001-Use-gnutls.patch
    %reconfigure
    %configure --disable-static \
        --disable-libcurl-option \
        --enable-threaded-resolver \
        --with-gnutls \
        --without-openssl \
        --without-ssl \
        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share %libdir%/pkgconfig /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
