name       : curl-gnutls
version    : 7.71.0
release    : 34
source     :
    - https://github.com/curl/curl/releases/download/curl-7_71_0/curl-7.71.0.tar.xz : cdf18794393d8bead915312708a9e5d819c6e9919de14b20d5c8e7987abd9772
homepage   : https://curl.haxx.se
license    : MIT
component  : binary.compat
emul32     : yes
summary    : curl-gnutls (GnuTLS version of curl)
description: |
    This package provides binary compatibility only and enables the running of content expecting a GnuTLS version of curl. It is forbidden to build against it.
builddeps  :
    - pkgconfig32(nettle)
    - pkgconfig32(p11-kit-1)
    - pkgconfig32(gnutls)
    - pkgconfig32(zlib)
    - libunistring-32bit-devel
    - libtool-32bit
    - gmp-32bit-devel
setup      : |
    %patch -N -p1 < $pkgfiles/0001-Use-gnutls.patch
    %reconfigure
    %configure --disable-static \
        --enable-threaded-resolver \
        --disable-libcurl-option \
        --with-gnutls \
        --with-ca-path=/etc/ssl/certs \
        --without-openssl \
        --without-ssl
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share %libdir%/pkgconfig /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
