name       : curl-gnutls
version    : 7.57.0
release    : 12
source     :
    - https://curl.haxx.se/download/curl-7.57.0.tar.xz : f5f6fd3c72b7b8389969f4fb671ed8532fa9b5bb7a5cae7ca89bc1cea45c7878
homepage   : https://curl.haxx.se
license    : GPL-3.0
component  : binary.compat
emul32     : yes
summary    : curl-gnutls (GnuTLS version of curl)
description: |
    This package provides binary compatibility only and enables the running of content expecting a GnuTLS version of curl. It is forbidden to build against it.
builddeps  :
    - pkgconfig32(nettle)
    - pkgconfig32(p11-kit-1)
    - pkgconfig32(gnutls)
    - pkgconfig32(zlib)
    - libunistring-32bit-devel
    - libtool-32bit
    - gmp-32bit-devel
setup      : |
    %patch -N -p1 < $pkgfiles/0001-Use-gnutls.patch
    %reconfigure
    %configure --disable-static \
        --disable-libcurl-option \
        --enable-threaded-resolver \
        --with-gnutls \
        --without-openssl \
        --without-ssl \
        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share %libdir%/pkgconfig /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
