name       : curl-gnutls
version    : 7.82.0
release    : 41
source     :
    - https://github.com/curl/curl/releases/download/curl-7_82_0/curl-7.82.0.tar.xz : 0aaa12d7bd04b0966254f2703ce80dd5c38dbbd76af0297d3d690cdce58a583c
homepage   : https://curl.haxx.se
license    : MIT
component  : binary.compat
emul32     : yes
summary    : GnuTLS version of curl
description: |
    This package provides binary compatibility only and enables the running of content expecting a GnuTLS version of curl. It is forbidden to build against it.
builddeps  :
    - pkgconfig32(nettle)
    - pkgconfig32(gnutls)
    - pkgconfig32(zlib)
    - patchelf
setup      : |
    %configure --disable-static \
        --enable-threaded-resolver \
        --disable-libcurl-option \
        --with-gnutls \
        --with-ca-path=/etc/ssl/certs
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries.
    for i in /usr/bin /usr/share %libdir%/pkgconfig /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too. Keep only versioned sonames.
    rm $installdir/%libdir%/*.so
    rm $installdir/%libdir%/*.la
    # Don't collide with OpenSSL-based curl.
    pushd $installdir/%libdir%
        for name in libcurl*; do
            gnuname=$(echo $name | sed 's|libcurl|libcurl-gnutls|')
            if [ -L $name ]; then
                patchelf --set-soname $gnuname $name
            fi
            mv $name $gnuname
        done
    popd
